server.port=8081

spring.application.name=ligas

spring.datasource.url=jdbc:mysql://localhost:3306/db_ligas
spring.datasource.username=root
spring.datasource.password=system


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true